<?php
/** @package Alunos::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("CadastroMap.php");

/**
 * CadastroDAO provides object-oriented access to the cadastro table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package Alunos::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class CadastroDAO extends Phreezable
{
	/** @var string */
	public $Nome;

	/** @var string */
	public $Email;

	/** @var string */
	public $Curso;

	/** @var string */
	public $Sexo;



}
?>